DELETE FROM `security_actionLabel` WHERE `action` LIKE 'News%' AND `language` = 'esp';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasEdit', 'Editar multimedia de novedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsEdit', 'Editar comentarios de novedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesEdit', 'Editar Novedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCaptchaGeneration', 'Generación de captcha', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasSortX', 'Ordenar contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsShow', 'Mostrar comentarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsChangeStatuses', 'Cambiar estado de comentarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasList', 'Listado de Novedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasGetImage', 'Obtener imagenes de novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCaptchaRefresh', 'Refrescar el captcha', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasDoEditX', 'Modificar información de contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesPreview', 'Vista previa de Novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesChangeStatusX', 'Modificar el estado de una novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesSearch', 'Buescar novedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsChangeStatusX', 'Cambiar estado del comentario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasGetSound', 'Obtener contenido de audio', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesSendToEmailX', 'Envío de novedad ', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsDoDelete', 'Eliminar comentario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasArticleList', 'Listado de contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasUpload', 'Subir contenido multimedia al servidor', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesGetThumbnail', 'Obtener miniatura de imagen de novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsList', 'Lista de comentarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesSendForm', 'Envío de novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsCommentsDoAddX', 'Agregar comentario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesList', 'Listado de novedades del sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesDoDelete', 'Eliminar Novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasGetVideo', 'Obtener contenido de video', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesView', 'Vista pública de la novedad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesChangeStatuses', 'Cambiar estado de nvedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsArticlesShow', 'Vista pública de novedades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('NewsMediasDoDelete', 'Eliminar contenido multimedia', 'esp');
