<?php

/**
 * Skeleton subclass for representing a row from the 'catalog_affiliateProductCode' table.
 *
 * Codigos de Productos por Afiliado
 *
 * This class was autogenerated by Propel on:
 *
 * 11/20/07 13:52:47
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class AffiliateProductCode extends BaseAffiliateProductCode {

  /**
  * Obtiene el producto asociado.
  *
  * @return Product Informacion del producto
  */
  function getProduct() {  
    $cond = new Criteria();
    $cond->add(ProductPeer::CODE, $this->getProductCode());
    $alls = ProductPeer::doSelect($cond);
    return $alls[0];  
  }

} // AffiliateProductCode
