DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Planning%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsXsEdit', 'Modificar indicador X', 'Modificar indicador X', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsSeriesEdit', 'Modificar series', 'Modificar series', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectTagsEdit', 'Modificar etiqueta', 'Modificar etiqueta', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesEdit', 'Modificar objetivo de impacto', 'Modificar objetivo de impacto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsEdit', 'Modificar obra', 'Modificar obra', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsYsEdit', 'Modificar indicador Y', 'Modificar indicador Y', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsEdit', 'Modificar indicador', 'Modificar indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsEdit', 'Editar proyecto', 'Editar proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesEdit', 'Editar proyecto operativo', 'Editar proyecto operativo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesEdit', 'Editar objetivo ministerial', 'Editar objetivo ministerial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningSetPlanning', 'Setear planeamiento', 'Setear planeamiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsShowHistoryX', 'Mostrar historial', 'Mostrar historial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesList', 'Lista de objetivos de impacto', 'Lista de objetivos de impacto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsList', 'Lista de obras', 'Lista de obras', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningActivityDocumentsListX', 'Lista de documentos', 'Lista de documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsXsDoDeleteX', 'Eliminar indicador X', 'Eliminar indicador X', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningTree', 'Arbol de planeamiento', 'Arbol de planeamiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsList', 'Lista de indicadores', 'Lista de indicadores', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesDoDelete', 'Eliminar objetivo de impacto', 'Eliminar objetivo de impacto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectives2Edit', 'Editar objetivos ministeriales', 'Editar objetivos ministeriales', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningActivitiesViewX', 'Ver actividad', 'Ver actividad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesDoDelete', 'Eliminar objetivo operativo', 'Eliminar objetivo operativo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsDoDelete', 'Eliminar obra', 'Eliminar obra', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsXsDoOrderByIndicatorX', 'Ordenar según indicador', 'Ordenar según indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsDoDelete', 'Eliminar indicador', 'Eliminar indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsShow', 'Mostrar proyecto', 'Mostrar proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsViewX', 'Ver proyecto', 'Ver proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesLogTabs', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsViewGraphX', 'Ver gráfico', 'Ver gráfico', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningSetPlanningX', 'Setear planeamiento', 'Setear planeamiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningRemoveBudgetItemRelationX', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsDoDelete', 'Eliminar proyecto', 'Eliminar proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningActivitiesDoDeleteX', 'Eliminar actividad', 'Eliminar actividad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningActivitiesEdit', 'Editar actividad', 'Editar actividad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningCakeByStatusColorXml', 'Gráfico de torta según color de estado', 'Gráfico de torta según color de estado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesViewX', 'Ver objetivo operativo', 'Ver objetivo operativo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsUpdateTagsX', 'Actualizar etiqueta', 'Actualizar etiqueta', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningActivitiesDoDelete', 'Eliminar actividad', 'Eliminar actividad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningDummy', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesShowHistoryX', 'Mostrar historial', 'Mostrar historial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsLogTabs', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningTreeView', 'Ver árbol', 'Ver árbol', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesShowHistoryX', 'Ver historial', 'Ver historial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesUpdateTabsX', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesUpdateTabsX', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsLogTabs', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsViewXml', 'Ver indicador en XML', 'Ver indicador en XML', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsUpdateIndicatorX', 'Actualizar indicador', 'Actualizar indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesViewX', 'Ver objetivo ministerial', 'Ver objetivo ministerial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningBarsQXml', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesViewX', 'Ver objetivo de impacto', 'Ver objetivo de impacto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningObjectsDoRemoveIndicatorX', 'Eliminar indicador', 'Eliminar indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsUpdateTabsX', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsSeriesDoDeleteX', 'Eliminar serie', 'Eliminar serie', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsSeriesDoOrderByIndicatorX', 'Ordenar series según indicadores', 'Ordenar series según indicadores', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningOperativeObjectivesList', 'Lista de objetivos operativos', 'Lista de objetivos operativos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningRemoveProgressRecordX', 'Eliminar registro de progreso', 'Eliminar registro de progreso', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesShowHistoryX', 'Mostrar historial', 'Mostrar historial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsDoEditX', 'Editar indicador', 'Editar indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsView', 'Ver indicador', 'Ver indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesList', 'Lista de objetivos ministeriales', 'Lista de objetivos ministeriales', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesUpdateTabsX', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningIndicatorsViewX', 'Ver indicador', 'Ver indicador', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectTagsList', 'Lista de etiquetas', 'Lista de etiquetas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesLogTabs', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningMinistryObjectivesDoDelete', 'Eliminar obejtivo ministerial', 'Eliminar obejtivo ministerial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsViewX', 'Ver obra', 'Ver obra', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningImpactObjectivesLogTabs', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningTreeNew', 'Nuevo árbol', 'Nuevo árbol', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningTreeDivs', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsUpdateTabsX', '', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningProjectsList', 'Lista de proyectos', 'Lista de proyectos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningConstructionsShowHistoryX', 'Mostrar historial', 'Mostrar historial', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningActivitiesList', 'Lista de actividades', 'Lista de actividades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PlanningObjectsDoAddIndicatorX', 'Agregar indicador', 'Agregar indicador', 'esp');
