<?php
require_once 'mer/om/BaseDocument.php';

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [10/23/06 13:29:49]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class Document extends BaseDocument {



  function checkPassword($password) {
	  if ($this->getPassword() == md5($password."ASD") ) {
				return true;
		}
		return false;
  }
}
