<?php
$GLOBALS['fc_config']['badWordSubstitute'] = '#$%^&*';
$GLOBALS['fc_config']['badWords'] = array (
  'asses' => 'arses',
  'asshole' => '@hole',
  'bitch' => 'b***h',
  'clit' => 'clit',
  'cum*' => 'cum*',
  'damn' => 'damn',
  'dildo' => 'dildo',
  'dink' => 'dink',
  'fuk' => 'fuk',
  'jism' => 'jism',
  'jiz' => 'jiz',
  'kock' => 'kock',
  'kum' => 'kum',
  '*mothafuck*' => '*mothafuck*',
  '*fuck*' => '*fuck*',
  'nigger' => 'nigger',
  'phuk' => 'phuk',
  'phuq' => 'phuq',
  'shit' => 'shit',
  'spunk' => 'spunk',
  'twat' => 'twat',
  'cock' => 'cock',
  'cunt' => 'cunt',
  'arses' => 'arses',
  '@hole' => '@hole',
  'cacheType' => '0',
  'cachePath' => '../temp/templates/cache/',
  'cacheFilePrefix' => '1892468974',
);
?>