DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Banners%' and `language` = '';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersOrderByZone', 'Order banners by zone', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersZonesEdit', 'Edit banner zone', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersWeightByZone', 'Weight banner display by zone', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersEdit', 'Edit banner', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersClientsEdit', 'Edit client', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersClientsDoDelete', 'Delete client', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersDoOrderByZoneX', 'Order banner by zone', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersStatsShow', 'Banners stats show', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersList', 'Banners list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersDoClickThru', 'Execute banner click thru', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersZonesDoDelete', 'Delete zone', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersDoDelete', 'Delete banner', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersContentStream', 'Stream banner contet', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersPreview', 'Banner preview', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersZonesDisplay', 'Display banner zone', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersZonesList', 'List banners zones', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BannersClientsList', 'List clients', 'eng');
