DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Panel%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelProjectsEdit', 'Modificar proyecto', 'Modificar proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelConstructionsEdit', 'Modificar obra', 'Modificar obra', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelSetPanelX', 'Setear tablero', 'Setear tablero', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelProjectsShow', 'Mostrar proyecto', 'Mostrar proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelConstructionsViewX', 'Ver obra', 'Ver obra', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelStrategicVisionHome', 'Visión estratégica', 'Visión estratégica', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelRelativeExpensesShow', 'Mostrar gastos relativos', 'Mostrar gastos relativos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelSetPanel', 'Setear tablero', 'Setear tablero', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelActivitiesViewX', 'Ver actividad', 'Ver actividad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelActivitiesEdit', 'Modificar actividad', 'Modificar actividad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelProjectsList', 'Lista de proyectos', 'Lista de proyectos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelImpactObjectivesListX', 'Lista de objetivos de impacto', 'Lista de objetivos de impacto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelResultsShow', 'Mostrar resultados', 'Mostrar resultados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelAchievementsShow', 'Mostrar logros', 'Mostrar logros', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelActivitiesList', 'Lista de actividades', 'Lista de actividades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelExpensesShow', 'Mostrar gastos', 'Mostrar gastos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelConstructionsList', 'Lista de obras', 'Lista de obras', 'esp');
