DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Panel%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelConstructionsEdit', 'Actualizar seguimiento de obras', 'Permite actualizar el seguimiento de obras', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelProjectsEdit', 'Actualizar seguimiento de proyectos', 'Permite actualizar el seguimiento de proyecto', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelAchievementsShow', 'Mostrar informe de logros', 'Muestra informe de logros', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelActivitiesEdit', 'Actualizar seguimiento de actividades', 'Permite actualizar seguimiento de actividades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelActivitiesList', 'Lista de actividades para seguimiento', 'Muestra el listado de actividades para seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelActivitiesViewX', 'Mostrar actividades en seguimiento', 'Muestra actividades en seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelConstructionsList', 'Listado de obras para seguimiento', 'Muestra el listado de obras para seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelConstructionsViewX', 'Mostrar obra en seguimiento', 'Muestra obra en seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelExpensesShow', 'Mostrar informe de gastos', 'Muestra informe de gastos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelImpactObjectivesListX', 'Listar objetivos de Impacto en seguimiento', 'Lista de objetivos de Impacto en seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelProjectsList', 'Listar proyectos para seguimiento', 'Lista de proyectos para seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelProjectsShow', 'Mostrar proyecto en seguimiento', 'Muestra proyecto en seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelRelativeExpensesShow', 'Mostrar informe de gastos relativos', 'Muestra informe de gastos relativos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelResultsShow', 'Mostrar informe de resultados', 'Muestra informe de resultados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelSetPanel', 'Setear funcionalidad de seguimiento', 'Setea el sistema en modo seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelSetPanelX', 'Setear funcionalidad de seguimiento', 'Setea el sistema en modo seguimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PanelStrategicVisionHome', 'Mostrar informe de Visión estratégica', 'Muestra informe de Visión estratégica', 'esp');
