DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Positions%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsEdit', 'Alta/Modificación de cargo/dependencia', 'Alta/Modificación de cargo/dependencia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsVersionsEdit', 'Modificar las versiones', 'Modifica información de versiones', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsAutocompleteListX', 'Listar cargos por consulta de autocompletar', 'Listado de cargos por consulta de autocompletar', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsChartView', 'Mostrar organigrama gráfico', 'Muestra el organigrama gráfico', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsDoDelete', 'Eliminar cargo o dependencia', 'Elimina cargo o dependencia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsGetAllParentsByPositionX', 'Obtener los posibles padres por tipo de posición', 'Obtienen los posibles padres por tipo de posición', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsList', 'Ver listado de cargos y dependencias', 'Muestra listado de cargos y dependencias', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsShow', 'Mostrar los objetivos de las dependencias o cargos', 'Muestra los objetivos de las dependencias o cargos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsTenuresDoDelete', 'Eliminar responsable a cargo de una posición', 'Elimina responsable a cargo de una posición', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsTenuresDoEdit', 'Modificar de un responsable a cargo', 'Alta/Modificación de un responsable a cargo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsUsersListX', 'Obtener listado de usuarios del autocompletar', 'Obtienen listado de usuarios del autocompletar', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('PositionsVersionsList', 'Ver listado de versiones', 'Muestra listado de versiones', 'esp');
