DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Positions%' AND `language` = 'eng';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsEdit', 'Edit position', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsVersionsEdit', 'Edit versions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsList', 'List positions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsTenuresDoDelete', 'Delete tenure from a position', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsDoDelete', 'Delete a position', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsUsersListX', 'Users list of autocomplete', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsVersionsList', 'Versions list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsGetAllParentsByPositionX', 'Obtain all possibl eparents by position', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsShow', 'Shows positions objectives', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsChartView', 'Organizational chart view', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('PositionsTenuresDoEdit', 'Edit a position tenure', 'eng');
