<?php

/**
 * Skeleton subclass for performing query and update operations on the 'MER_ActorActiveQuestion' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Aug 17 15:49:03 2006
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer
 */	
class ActorActiveQuestionPeer extends BaseActorActiveQuestionPeer {

	/**
	* Obtiene un ActorActiveQuestion.
	*
	* @return ActorActiveQuestion ActorActiveQuestion
	*/
  function get($actor,$question) {
   	$obj = ActorActiveQuestionPeer::retrieveByPK($actor->getId(),$question->getId());
		return $obj;
  }
  
	/**
	* Elimina un ActorActiveQuestion.
	*
	* @return void
	*/
  function delete($actor,$question) {
   	$obj = ActorActiveQuestionPeer::retrieveByPK($actor->getId(),$question->getId());
		if ( !empty($obj) ) {
			$obj->delete();
		}
		return;
	}

} // ActorActiveQuestionPeer
