<?php


/**
 * Skeleton subclass for representing a row from the 'MER_ActorActiveQuestion' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Aug 17 15:49:03 2006
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer
 */	
class ActorActiveQuestion extends BaseActorActiveQuestion {

} // ActorActiveQuestion
