<?php

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [Tue Jul 18 18:52:56 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class Answer extends BaseAnswer {
	function __toString(){
		if ($question = $this->getQuestion()){
			switch ($question->getType()){
				case QUESTION_TYPE_OPTIONS:
					$options = $question->getOptions();
					$answer = null;
					foreach ($options as $option){
						if ($option->getValue() == $this->getAnswer()){
							$answer = $option->getText();
							break;
						}
					}
					break;
				case QUESTION_TYPE_BOOLEAN:
					if ($answer === ''){
						$answer = 'N/A';
					}else{
						$answer = ($answer) ? "yes" : "no";
					}
					break;
				default:
				case QUESTION_TYPE_TEXT:
					$answer = $this->answer;
					break;
			}
			return $answer. " <span class='units'>".$question->getUnit()."</span>";
		}
	}
}
