<?php
/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [Tue Jul 18 18:52:56 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class FormSectionPeer extends BaseFormSectionPeer {

  /**
  * Crea un formSection nuevo.
  *
  * @param string $name name del form
  * @param int $relationship relationship del form
  * @param int $rootSectionId rootSectionId del form
  * @return boolean true si se creo el form correctamente, false sino
	*/
	function create($title,$parentSectionId=null) {
		$section = new FormSection();
		$section->setTitle($title);
		if (!empty($parentSectionId))
			$section->setParentSectionId($parentSectionId);
		$section->save();
		return $section->getId();
	}
	
	/**
	* Elimina un formSection a partir del id.
	*
  * @param int $id id del formSection
	*	@return boolean true si se elimino correctamente el formSection, false sino
	*/
  function delete($id) {
  	$obj = FormSectionPeer::retrieveByPK($id);
    if (!empty($obj))
			$obj->delete();
		return true;
  }

}
