<?php

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [Tue Jul 18 18:52:56 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class Form extends BaseForm {
	function getRootSection(){
		return $this->getFormSection();
	}
	function smarty(){
		$ret['form'] = $this;
		$ret['sections'] = array();
		$ret['sections'][]=$this->getRootSection()->getSectionsAndQuestions();
		return $ret;		
	}
	
	function getAllQuestions() {
		$section = $this->getRootSection();
		$questions = $section->getAllQuestions();
		return $questions;
	}
}
