<?php
require_once 'mer/om/BaseGraphRelation.php';

require_once("GraphRelationQuestionPeer.php");

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [11/06/06 18:31:19]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GraphRelation extends BaseGraphRelation { 

	function getQuestions() {
		$grqs = GraphRelationQuestionPeer::getByGraph($this);
		$questions = array();
		foreach ($grqs as $grq) {
			$questions[] = $grq->getQuestion();
		}
		return $questions;
	}
	
	function changeJudgement($judgement) {
		$this->setJudgement($judgement);
		$this->setOld(0);
		$this->save();
	}

}
