<?php
// The parent class
require_once 'mer/om/BaseGraphRelationQuestionPeer.php';

// The object class
include_once 'mer/GraphRelationQuestion.php';

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [11/06/06 18:33:49]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GraphRelationQuestionPeer extends BaseGraphRelationQuestionPeer {

	function getByGraph($graph) {
		$crit = new Criteria();
		$crit->add(GraphRelationQuestionPeer::GRAPHRELATIONID,$graph->getId());
		$todosObj = GraphRelationQuestionPeer::doSelectJoinQuestion($crit);
		return $todosObj;
	}
	
	function deleteByGraph($graph) {
		$crit = new Criteria();
		$crit->add(GraphRelationQuestionPeer::GRAPHRELATIONID,$graph->getId());
		$objs = GraphRelationQuestionPeer::doSelect($crit);
		foreach ($objs as $obj) {
			$obj->delete();
		}
		return true;
	}

}
