<?php
require_once 'mer/om/BaseGraph.php';

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [08/30/06 00:32:14]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class Graph extends BaseGraph {

}
