<?php

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [08/30/06 01:44:25]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GraphActorPeer extends BaseGraphActorPeer {

	function setJudgement($graph,$actor,$category,$judgement) {
		$obj = GraphActorPeer::retrieveByPK($graph,$actor);
		if ( empty($obj) ) {
			$obj = new GraphActor();
			$obj->setGraphId($graph);
			$obj->setActorId($actor);
			$obj->setCategoryId($category);
		}
		$obj->setJudgement($judgement);
		$obj->setOld(0);
		$obj->save();
	}
	
	function setOldByActor($actor) {
		$crit = new Criteria();
		$crit->add(GraphActorPeer::ACTORID ,$actor->getId());
		$graphs = GraphActorPeer::doSelect($crit);
		foreach ($graphs as $graph) {
			$graph->setOld(1);
			$graph->save();                            	
		}
	}

}
