<?php
// The parent class
require_once 'mer/om/BaseGraphModelJudgementPeer.php';

// The object class
include_once 'mer/GraphModelJudgement.php';

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [08/28/06 20:03:46]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GraphModelJudgementPeer extends BaseGraphModelJudgementPeer {

  /**
  * Obtiene todos los juicios para un grafico.
	*
	* @param int $graphId Id del grafico
	*	@return array Informacion sobre todos los juicios
	*/
	function getAllByGraph($graphId) {
		$cond = new Criteria();
		$cond->add(GraphModelJudgementPeer::GRAPHID, $graphId);
		$cond->addAscendingOrderByColumn(GraphModelJudgementPeer::QUADRANT);
		$todosObj = GraphModelJudgementPeer::doSelect($cond);
		return $todosObj;
  }
  
  /**
  * Obtiene el juicios para un grafico y cuadrante.
	*
	* @param int $graphId Id del grafico
	* @param int $quadrant Numero de cuadrante
	*	@return array Informacion sobre el juicio
	*/
	function get($graphId,$quadrant) {
	  $graphModelJudgement = GraphModelJudgementPeer::retrieveByPK($graphId,$quadrant);
		return $graphModelJudgement;
  }

}
