<?php
// The parent class
require_once 'mer/om/BaseGraphPeer.php';

// The object class
include_once 'mer/Graph.php';

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [08/30/06 00:32:14]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GraphPeer extends BaseGraphPeer {

  /**
  * Obtiene todos los graficos para un actor.
	*
	*	@param int $actor Id de actor
	*	@return array Informacion sobre los graficos
  */
	function getAllByActor($actor) {
		$category = ActorPeer::get($actor)->getCategoryId();
		$cond = new Criteria();
		$cond->add(GraphPeer::ACTORID, $actor);
		$cond->add(GraphPeer::CATEGORYID, $category);
		$cond2 = new Criteria();
		$todosObj = GraphModelPeer::doSelect($cond2);
		for ($i=0; i<count($todosObj); $i++) {
    	$todosObj[$i]->judgement =
		}
		return $todosObj;
  }

}
