<?php

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [08/30/06 01:44:25]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GraphCategoryPeer extends BaseGraphCategoryPeer {

	function setJudgement($graph,$category,$judgement) {
		$obj = GraphCategoryPeer::retrieveByPK($graph,$category);
		if ( empty($obj) ) {
			$obj = new GraphCategory();
			$obj->setGraphId($graph);
			$obj->setCategoryId($category);
		}
		$obj->setJudgement($judgement);
		$obj->setOld(0);
		$obj->save();
	}
	
	function setOldByCategory($category) {
		$crit = new Criteria();
		$crit->add(GraphCategoryPeer::CATEGORYID ,$category->getId());
		$graphs = GraphCategoryPeer::doSelect($crit);
		foreach ($graphs as $graph) {
			$graph->setOld(1);
			$graph->save();
		}
	}	

}
