<?php

/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [08/30/06 00:32:14]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class JudgementActorPeer extends BaseJudgementActorPeer {

  /**
  * Obtiene la informacion de un juicio.
  *
  * @param int $actor Id del actor
  * @return JudgementActor Informacion del juicio
  */
	function get($actor) {
  	$obj = JudgementActorPeer::retrieveByPK($actor);
  	return $obj;
	}
	
	function setJudgement($actor,$mark,$judgement) {
		$obj = JudgementActorPeer::retrieveByPK($actor);
		if ( empty($obj) ) {
			$obj = new JudgementActor();
			$obj->setActorId($actor);
		}
		$obj->setMark($mark);		
		$obj->setJudgement($judgement);
		$obj->setOld(0);
		$obj->save();
	}

}
