<?php
/** 
 * The skeleton for this class was autogenerated by Propel on:
 *
 * [11/02/06 21:51:33]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class RelationshipActiveQuestionPeer extends BaseRelationshipActiveQuestionPeer {

	/**
	* Obtiene un RelationshipActiveQuestion.
	*
	* @return RelationshipActiveQuestion RelationshipActiveQuestion
	*/
  function get($actor1,$actor2,$question) {
   	$obj = RelationshipActiveQuestionPeer::retrieveByPK($actor1->getId(),$actor2->getId(),$question->getId());
		return $obj;
  }
  
	/**
	* Elimina un RelationshipActiveQuestion.
	*
	* @return void
	*/
  function delete($actor1,$actor2,$question) {
   	$obj = RelationshipActiveQuestionPeer::retrieveByPK($actor1->getId(),$actor2->getId(),$question->getId());
		if ( !empty($obj) ) {
			$obj->delete();
		}
		return;
	}

}
