DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Common%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonActionLogsPurge', 'Eliminar registros históricos', 'Eliminar registros históricos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsEdit', 'Editar suscripción de alertas', 'Editar suscripción de alertas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonConfigEdit', 'Modificar estructura de configuración', 'Modificar estructura de configuración', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonConfigSet', 'Modificar valores de configuración', 'Modificar valores de configuración', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonLogin', 'Ingreso de usuarios al sistema', 'Ingreso de usuarios al sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsEdit', 'Editar correos internos', 'Editar correos internos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsEdit', 'Editar elementos del menú', 'Editar elementos del menú', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordRecovery', 'Recuper contraseña', 'Recuper contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsEdit', 'Editar suscripción programada', 'Editar suscripción programada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonActionLogsList', 'Ver listado de histórico de operaciones', 'Ver listado de histórico de operaciones', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsDoAddUserX', 'Agregar usuario a suscripción de alerta', 'Agregar usuario a suscripción de alerta', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsDoDelete', 'Eliminar suscripción de alerta', 'Eliminar suscripción de alerta', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsDoDeleteUserX', 'Eliminar usuario de suscripción de alerta', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsGetEntityFields', 'Obtener campos para fijar alertas', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsList', 'Lista de suscripciones de alertas disponibles', 'Lista de suscripciones de alertas disponibles', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonCaptchaGeneration', 'Generar imagen de seguridad', 'Generar imagen de seguridad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonConfigView', 'Ver valores de configuración', 'Ver valores de configuración', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonDoLogout', 'Salida dle sistema', 'Salida dle sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonGenerateJs', 'Generar archivo JavaScript', 'Generar archivo JavaScript', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonIndex', 'Redireccionamiento al indice', 'Redireccionamiento al indice', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsDoDeleteX', 'Eliminar correo interno', 'Eliminar correo interno', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsDoMarkAsReadX', 'Marcar mail interno como leido', 'Marcar mail interno como leido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsList', 'Lista de mensajes de correo internos', 'Lista de mensajes de correo internos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsView', 'Ver mensaje de correo interno', 'Ver mensaje de correo interno', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsViewX', 'Ver mensaje de correo interno', 'Ver mensaje de correo interno', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonJs', 'Genera archivo de JavaScript', 'Genera archivo de JavaScript', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMaintenance', 'Redireccionamiento de Sistema en Mantenimiento', 'Redireccionamiento de Sistema en Mantenimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsActionsAutocompleteListX', 'Ayuda para autocompletar con acciones existentes', 'Ayuda para autocompletar con acciones existentes', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsDoDeleteX', 'Eliminar item del menú', 'Eliminar item del menú', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsDoEditOrderX', 'Cambiar el orden de items del menú', 'Cambiar el orden de items del menú', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsGetActionInfoX', 'Obtener información para generación de menu', 'Obtener información para generación de menu', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsList', 'Listado de elementos dle menu', 'Listado de elementos dle menu', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsShow', 'Mostrar menu', 'Mostrar menu', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonNestedSetDoOrderByParentX', 'Ordenar por padre', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonNestedSetOrderByParent', 'Ordenar por padre', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordDoChangeForRecovery', 'Cambiar contraseña desde recuperación', 'Cambiar contraseña desde recuperación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordRecoveryConfirmation', 'Confirmarrecuperación de contraseña', 'Confirmarrecuperación de contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordRecoverySendConfirmationRequest', 'Enviar confirmación de recuperaciónd e contraseña', 'Enviar confirmación de recuperaciónd e contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsDoAddUserX', 'Agregar usuario a suscripción', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsDoDelete', 'Eliminar suscripción', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsDoDeleteUserX', 'Eliminar usuario de suscripción', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsGetEntityFields', 'Obtener campos para suscripción de agenda', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsList', 'Listar alertas de suscripción', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSendAlerts', 'Envío de alertas', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSendSchedules', 'Envia vencimientos', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSetLanguage', 'Condifura el idioma de la aplicación', 'Condifura el idioma de la aplicación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonTemplatePublic', 'Muestra un external público', 'Muestra un external público', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonWelcome', 'Acción de bienvenida del usuario', 'Acción de bienvenida del usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('Js', 'Entregar archivos de javascript', 'Entregar archivos de javascript', 'esp');
