DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Common%' AND `language` = 'eng';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonActionLogsPurge', 'Purge action logs', 'Purge action logs', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsEdit', 'Edit alert subscriptions', 'Edit alert subscriptions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonConfigEdit', 'Edit config variables', 'Edit config variables', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonConfigSet', 'Set config values', 'Set config values', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonLogin', 'Users login', 'Users login', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsEdit', 'Edit internal mails', 'Edit internal mails', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsEdit', 'Edit menu items', 'Edit menu items', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordRecovery', 'Password recovery', 'Password recovery', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsEdit', 'Edit schedule subscription', 'Edit schedule subscription', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonActionLogsList', 'List actions logs', 'List actions logs', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsDoAddUserX', 'Add user to alert subscription', 'Add user to alert subscription', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsDoDelete', 'Delete alert subscription', 'Delete alert subscription', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsDoDeleteUserX', 'Delete user from alert subscription', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsGetEntityFields', 'Get entity fields to subscribe alerts', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonAlertsSubscriptionsList', 'List alert subscriptions', 'List alert subscriptions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonCaptchaGeneration', 'Generates captcha', 'Generates captcha', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonConfigView', 'View config values', 'View config values', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonDoLogout', 'Common logout', 'Common logout', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonGenerateJs', 'Generates JavaScript file', 'Generates JavaScript file', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonIndex', 'Index redirect', 'Index redirect', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsDoDeleteX', 'Delete internal mail', 'Delete internal mail', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsDoMarkAsReadX', 'Mark internal mail as read', 'Mark internal mail as read', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsList', 'Internal mail list', 'Internal mail list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsView', 'View Internal mail message', 'View Internal mail message', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonInternalMailsViewX', 'View Internal mail message', 'View Internal mail message', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonJs', 'Generates JavaScript file', 'Generates JavaScript file', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMaintenance', 'System under management redirect', 'System under management redirect', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsActionsAutocompleteListX', 'Autocomplete actions for menu', 'Autocomplete actions for menu', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsDoDeleteX', 'Delete menu item', 'Delete menu item', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsDoEditOrderX', 'Edit menu items order', 'Edit menu items order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsGetActionInfoX', 'Get menu item info', 'Get menu item info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsList', 'List menu items', 'List menu items', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonMenuItemsShow', 'Show menu', 'Show menu', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonNestedSetDoOrderByParentX', 'Order by partent', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonNestedSetOrderByParent', 'Order by partent', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordDoChangeForRecovery', 'Change password from recovery', 'Change password from recovery', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordRecoveryConfirmation', 'Password recovery confirmation', 'Password recovery confirmation', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonPasswordRecoverySendConfirmationRequest', 'Send password recovery confirmation', 'Send password recovery confirmation', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsDoAddUserX', 'Add usert to alert subscription', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsDoDelete', 'Delete subscriotion', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsDoDeleteUserX', 'Delete user from subscriotion', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsGetEntityFields', 'Get entity fields to schedude subscription', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSchedulesSubscriptionsList', 'List subscriotion schedules', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSendAlerts', 'Send alerts', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSendSchedules', 'Send schedules', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonSetLanguage', 'Set application language', 'Set application language', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonTemplatePublic', 'Show public external', 'Show public external', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CommonWelcome', 'Common User welcome', 'Common User welcome', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('Js', 'Display js files', 'Display js files', 'eng');
