DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Users%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersEdit', 'Alta/Modificación de usuarios de sistema', 'Alta/Modificación de usuarios de sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersLogin', 'Ingresar al sistema', 'Ingreso al sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordChange', 'Modificar contraseña', 'Modificación de contraseña de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersAutocompleteListX', 'Mostrar listado de autocompletar con usuarios', 'Muestra listado de autocompletar con usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoActivate', 'Activación de usuario', 'Activación de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoActivateX', 'Activar usuario', 'Activa usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoAddToGroupX', 'Agregar usuario a grupo', 'Agrega usuario a grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoDelete', 'Eliminar usuario', 'Elimina usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoDeleteFromGroupX', 'Eliminar usuario de grupo', 'Elimina usuario de grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoEditInfoX', 'Editar información de usuario', 'Edita información de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoLinkToSupplier', 'Vincular usuario a proveedor', 'Vincula usuario a proveedor', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoLogout', 'Salir del sistema', 'Salir del sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersDoRemoveFromGroup', 'Remover usuario de grupo', 'Remueve un usuario de un gripo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersEditInfo', 'Modificar Información del Usuario', 'Modifica Información del Usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersGroupsDoAddCategoryToGroup', 'Agregar categoría a grupo', 'Agregar relación entre categoría y grupo de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersGroupsDoDelete', 'Eliminar grupo', 'Elimina grupo de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersGroupsDoEdit', 'Editar grupo de usuarios', 'Edita grupo de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersGroupsDoRemoveCatFromGroup', 'Eliminar categoría asociada a un grupo', 'Elimina relación de categoría con un grupo de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersGroupsList', 'Listar grupos de usuarios', 'Lista de grupos de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersLevelsDoDelete', 'Eliminar nivel de usuario', 'Elimina nivel de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersLevelsDoEdit', 'Editar nivel de usuario', 'Edita nivel de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersLevelsList', 'Listar niveles de usuario', 'Listado de niveles de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersList', 'Listr usuarios', 'Listado de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersLoginMaintenance', 'Ingresar al sistema en mantenimiento', 'Ingreso al sistema en mantenimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordDoChangeForRecovery', 'Cambiar contraseña recuperada', 'Cambia contraseña luego de ser recuperada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordDoRecover', 'Realizar solicitud de recupero de contraseña', 'Realiza solicitud de recupero de contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordRecovery', 'Mostrar solicitud de recupero de contraseña', 'Muestra solicitud de recupero de contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordRecoveryConfirmation', 'Confirmar recupero de contraseña', 'Confirma recupero de contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordRecoveryDoRequest', 'Generar solicitud de recuperación de contraseña', 'Genera solicitud de recuperación de contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersPasswordResetX', 'Resetear contraseña', 'Resetear contraseña por ajax', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersValidationPasswordX', 'Verificar contraseña actual para su modificación', 'Verifica contraseña actual para su modificación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersValidationUsernameX', 'Verificar validez/disponibilidad de nombre de usuario', 'Verifica validez/disponibilidad de nombre de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('UsersWelcome', 'Página de bienvenida al usuario', 'Muestra página de bienvenida al usuario', 'esp');
