DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Documents%' AND `language` = 'esp';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsEdit', 'Permite dar de alta o editar documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsKeyWordEdit', 'Editar palabra clave', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsList', 'Muestra el listado de documentos disponible', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsCategoriesList', 'Lista documentos por categoría', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsBase', 'Funcionalidades comunes', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsDoDownload', 'Permite la descarga de documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsDoDeleteX', 'Eliminar documento ', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsDoDelete', 'Elimina documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsShow', 'Listado público de documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsKeyWordList', 'Obtener listado de palabras clave', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsKeyWordDoDelete', 'Eliminar palabra clave', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('DocumentsUpload', 'Agregar documento', 'esp');
