<?php

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [07/27/06 17:46:21]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package mer 
 */
class GroupCategory extends BaseGroupCategory {

}
