DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Calendar%' AND `language` = 'esp';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasEdit', 'Editar contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsEdit', 'Editar evento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsWeek', 'Vista pública de eventos por semana', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasEventList', 'Listado de contenidos multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsView', 'Vista pública de evento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsGetThumbnail', 'Obtener miniatura de imagen de un evento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasDoEditX', 'Modificar información de contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsMonth', 'Vista pública de eventos por mes', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsDoDelete', 'Eliminar evento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsShow', 'Vista publica de eventos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsSearch', 'Búsqueda de eventos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsChangeStatuses', 'Cambiar estado de evento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsList', 'Listado de eventos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasList', 'Listado de contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasUpload', 'Subir contenido multimedia ', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsChangeStatusX', 'Modificar estado de un evento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasGetImage', 'Obtener imagen', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasDoDelete', 'Eliminar contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasSortX', 'Modificar orden de contenido multimedia', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsPreview', 'Vista previa de evento', 'esp');
