DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Blog%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCategoriesEdit', 'Editar categorías del blog', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsEdit', 'Editar comentarios de entradas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogEdit', 'Editar entradas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogTagsEdit', 'Editar etiquetas del blog', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCategoriesDoDelete', 'Eliminar categorías', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCategoriesList', 'Listado de Categorías', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogChangeStatuses', 'Cambiar estado de entradas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogChangeStatusX', 'Modificar el estado de una entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsChangeStatuses', 'Cambiar estado de comentarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsChangeStatusX', 'Cambiar estado del comentario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsDoAddX', 'Agregar comentario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsDoDelete', 'Eliminar comentario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsList', 'Lista de comentarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogCommentsShow', 'Mostrar comentarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogDoAddTagToEntryX', 'Agregar etiqueta a entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogDoDelete', 'Eliminar entradas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogDoDeleteTagFromEntryX', 'Remover etiqueta de entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogList', 'Listado de novedades del sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogPreview', 'Vista previa de entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogSearch', 'Buescar entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogSendForm', 'Envío de entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogSendToEmailX', 'Envío de entrada ', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogShow', 'Vista pública de entrada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogTagsDoDelete', 'Eliminar etiqueta', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogTagsList', 'Listado de etiquetas', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('BlogView', 'Vista pública de la entrada', 'esp');
