<?php

/**
 * Skeleton subclass for representing a row from the 'catalog_affiliateProduct' table.
 *
 * Precios de Productos por Afiliado
 *
 * This class was autogenerated by Propel on:
 *
 * Wed Oct 17 15:16:48 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class AffiliateProduct extends BaseAffiliateProduct {

} // AffiliateProduct
