DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Calendar%' AND `language` = 'eng';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasEdit', 'Media edit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsEdit', 'Event edit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsWeek', 'Events weekly view', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasEventList', 'Media list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsView', 'View calendar event', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsGetThumbnail', 'Show calendar thumbnail', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasDoEditX', 'Edit media', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsMonth', 'Calendar events monthly view', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsDoDelete', 'Delete event', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsShow', 'Public calendar events view', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsSearch', 'Search events', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsChangeStatuses', 'Change calendar events satuses', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsList', 'Calendar events list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasList', 'Calendar media list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasUpload', 'Upload calendar media', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsChangeStatusX', 'Change event status', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasGetImage', 'Show calendar images', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasDoDelete', 'Delet calendar media image', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarMediasSortX', 'Sort media', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CalendarEventsPreview', 'Calendar event preview', 'eng');
