<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /var/www/support/WEB-INF/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'application' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost; dbname=support',
        'user' => 'root',
        'password' => 'cavs113',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
      ),
    ),
    'default' => 'application',
  ),
  'debugpdo' => 
  array (
    'logging' => 
    array (
      'details' => 
      array (
        'method' => 
        array (
          'enabled' => true,
        ),
        'time' => 
        array (
          'enabled' => true,
        ),
        'mem' => 
        array (
          'enabled' => true,
        ),
      ),
    ),
  ),
  'log' => 
  array (
    'type' => 'file',
    'name' => 'propel.log',
    'ident' => 'application',
    'level' => '7',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'application-classmap.php');
return $conf;