<?php

require_once 'import/classes/om/BaseProductRequestConfirmation.php';


/**
 * Skeleton subclass for representing a row from the 'productRequestConfirmation' table.
 *
 * Confirmacion por parte del cliente a cada pedido de producto
 *
 * This class was autogenerated by Propel on:
 *
 * 12/05/07 13:19:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class ProductRequestConfirmation extends BaseProductRequestConfirmation {

} // ProductRequestConfirmation
