<?php

  // include base peer class
  require_once 'import/classes/om/BaseProductSupplierPeer.php';

  // include object class
  include_once 'import/classes/ProductSupplier.php';


/**
 * Skeleton subclass for performing query and update operations on the 'import_productSupplier' table.
 *
 * Relacion Productos Proveedores
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:07:45 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class ProductSupplierPeer extends BaseProductSupplierPeer {

} // ProductSupplierPeer
