<?php

require_once 'import/classes/om/BaseSupplierUser.php';


/**
 * Skeleton subclass for representing a row from the 'SupplierUser' table.
 *
 * Users / Suppliers
 *
 * This class was autogenerated by Propel on:
 *
 * 12/05/07 13:19:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierUser extends BaseSupplierUser {

} // SupplierUser
