<?php

  require_once('import/classes/SupplierQuoteHistory.php');

  // include base peer class
  require_once 'import/classes/om/BaseSupplierQuotePeer.php';

  // include object class
  include_once 'import/classes/SupplierQuote.php';


/**
 * Skeleton subclass for performing query and update operations on the 'import_supplierQuote' table.
 *
 * Cotizacion de Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierQuotePeer extends BaseSupplierQuotePeer {

  private $supplierId = '';

  /**
   * Devuelve los nombres de los estados del cleinte
   */					
  public function getStatusNamesAdmin() {
		return array_keys($this->statusNamesAdmin);
  }

  /**
   * Fija un filtro por supplier
   * @param Integer $supplierId id de supplier
   */
  public function setSupplierId($supplierId) {
	$this->supplierId = $supplierId;
  }
	
  /**
  * Obtiene la cantidad de filas por pagina por defecto en los listado paginados.
  *
  * @return int Cantidad de filas por pagina
  */
  function getRowsPerPage() {
    global $system;
    return $system["config"]["system"]["rowsPerPage"];
  }
  
  /**
  * Crea un supplier quote nuevo.
  *
  * @param array $params Array asociativo con los atributos del objeto
  * @return boolean true si se creo correctamente, false sino
  */  
  function create($params) {
    try {
      $supplierquoteObj = new SupplierQuote();
      foreach ($params as $key => $value) {
        $setMethod = "set".$key;
        if ( method_exists($supplierquoteObj,$setMethod) ) {          
          if (!empty($value))
            $supplierquoteObj->$setMethod($value);
          else
            $supplierquoteObj->$setMethod(null);
        }
      }
      $supplierquoteObj->save();
      return true;
    } catch (Exception $exp) {
      return false;
    }         
  }  
  
  /**
  * Actualiza la informacion de un supplier quote.
  *
  * @param array $params Array asociativo con los atributos del objeto
  * @return boolean true si se actualizo la informacion correctamente, false sino
  */  
  function update($params) {
    try {
      $supplierquoteObj = SupplierQuotePeer::retrieveByPK($params["id"]);    
      if (empty($supplierquoteObj))
        throw new Exception();
      foreach ($params as $key => $value) {
        $setMethod = "set".$key;
        if ( method_exists($supplierquoteObj,$setMethod) ) {          
          if (!empty($value))
            $supplierquoteObj->$setMethod($value);
          else
            $supplierquoteObj->$setMethod(null);
        }
      }
      $supplierquoteObj->save();
      return true;
    } catch (Exception $exp) {
      return false;
    }         
  }    

	/**
	* Elimina un supplier quote a partir de los valores de la clave.
	*
  * @param int $id id del supplierquote
	*	@return boolean true si se elimino correctamente el supplierquote, false sino
	*/
  function delete($id) {
  	$supplierquoteObj = SupplierQuotePeer::retrieveByPK($id);
    $supplierquoteObj->delete();
		return true;
  }

  /**
  * Obtiene la informacion de un supplier quote.
  *
  * @param int $id id del supplierquote
  * @return array Informacion del supplierquote
  */
  function get($id) {
		$supplierquoteObj = SupplierQuotePeer::retrieveByPK($id);
    return $supplierquoteObj;
  }

  /**
  * Obtiene todos los supplier quotes.
	*
	*	@return array Informacion sobre todos los supplierquotes
  */
	function getAll() {
		$cond = new Criteria();
		$alls = SupplierQuotePeer::doSelect($cond);
		return $alls;
  }
  
  /**
  * Obtiene todos los supplier quotes paginados.
  *
  * @param int $page [optional] Numero de pagina actual
  * @param int $perPage [optional] Cantidad de filas por pagina
  *	@return array Informacion sobre todos los supplierquotes
  */
  function getAllPaginated($page=1,$perPage=-1) {  
    if ($perPage == -1)
      $perPage = 	SupplierQuotePeer::getRowsPerPage();
    if (empty($page))
      $page = 1;
    $cond = new Criteria();     
    $pager = new PropelPager($cond,"SupplierQuotePeer", "doSelect",$page,$perPage);
    return $pager;
   }    	

   public function createFromClientQuote($supplier,$incoterm,$port,$clientQuote,$items) {
		
		try {
			
			$supplierQuote = new SupplierQuote();
			$supplierQuote->setSupplier($supplier);
			$supplierQuote->setClientQuoteId($clientQuote->getId());
			$supplierQuote->setCreatedAt(time());
			$supplierQuote->setStatus(SupplierQuote::STATUS_NEW);
			$supplierQuote->setTimestampStatus(time());
			$supplierQuote->setSupplierAccessToken(SupplierQuotePeer::generateRandomSupplierAccessCode());

			foreach ($items as $clientQuoteItem) {

				$supplierQuoteItem = new SupplierQuoteItem();
				$supplierQuoteItem->setProductId($clientQuoteItem->getProductId());
				$supplierQuoteItem->setClientQuoteItem($clientQuoteItem);
				$supplierQuoteItem->setQuantity($clientQuoteItem->getQuantity());
				$supplierQuoteItem->setIncoterm($incoterm);
				$supplierQuoteItem->setPort($port);
				$supplierQuoteItem->setStatus(SupplierQuoteItem::STATUS_NEW);
				
				$supplierQuote->addSupplierQuoteItem($supplierQuoteItem);
				
			}
			
			$supplierQuote->save();
			
			$supplierQuote->saveCurrentStatusOnHistory();
			
		} catch (PropelException $e) {

			return false;
		}
		
		return $supplierQuote;
   }

	/**
	 * Generador de codigos de Acceso para proveedor
	 * @return string
	 */
	public function generateRandomSupplierAccessCode() {
		return sha1(time() . 'anmaga');
	}
	
	public function getByAccessToken($token) {
		
		$criteria = new Criteria();
		$criteria->add(SupplierQuotePeer::SUPPLIERACCESSTOKEN,$token);
		$result = SupplierQuotePeer::doSelect($criteria);
		
		return $result[0];
		
	}

  /**
   * Genera una criteria segun la informacion introducida para filtros
   * @return Criteria instancia de criteria
   */
  private function getFilterCriteria() {
	$criteria = New Criteria();
	
	if (!empty($this->supplierId)) {
		$criteria->add(SupplierQuotePeer::SUPPLIERID,$this->supplierId);
	}
	
	return $criteria;
  }

  /**
  * Obtiene todos los supplier quotes paginados aplicando los filtros.
  *
  * @param int $page [optional] Numero de pagina actual
  * @param int $perPage [optional] Cantidad de filas por pagina
  *	@return array Informacion sobre todos los supplierquotes
  */
  public function getAllPaginatedFiltered($page=1,$perPage=-1) {  
    if ($perPage == -1)
      $perPage = 	SupplierQuotePeer::getRowsPerPage();
    if (empty($page))
      $page = 1;
    $cond = $this->getFilterCriteria();   
    $pager = new PropelPager($cond,"SupplierQuotePeer", "doSelect",$page,$perPage);
    return $pager;
   }    	


} // SupplierQuotePeer
