<?php

  // include base peer class
  require_once 'import/classes/om/BaseSupplierUserPeer.php';

  // include object class
  include_once 'import/classes/SupplierUser.php';


/**
 * Skeleton subclass for performing query and update operations on the 'SupplierUser' table.
 *
 * Users / Suppliers
 *
 * This class was autogenerated by Propel on:
 *
 * 12/05/07 13:19:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierUserPeer extends BaseSupplierUserPeer {

	/*
	 * Obtiene el supplier asignado a un user id, 
	 * si el mismo esta asignado.
	 *
	 * @param $userId id de usuario
	 * @return instancia de supplier si existe, o false si no existe.
	 *
	 */
	function getSupplierByUser($userId) {
	
		$crit = new Criteria();
		$crit->add(SupplierUserPeer::USERID  , $userId);
		$result = SupplierUserPeer::doSelect($crit);
		if (empty($result))
			return false;
		//sino devuelvo el primero
		return $result[0];

	}

} // SupplierUserPeer
