DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Affiliates%' AND `language` = 'esp';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesEdit', 'Editar información de Afiliados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLogin', 'Ingreso al sistema de usuariso de afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersPasswordRecovery', 'Recuperación de contraseña de usuariso de afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesAddAffiliate', 'Agregar afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesBranchsEdit', 'Modificar información de sucursal', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoEditUser', 'Guardar cambios de usuarios de afiliados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesViewAffiliate', 'Ver información de afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesDoDelete', 'Eliminar afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoAddCategory', 'Agregar categoría a grupo de usuariso afiliados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoEdit', 'Modificar grupos de usuariso de afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesBranchsList', 'Listado de sucursales de afiliados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersList', 'Listado de usuariso por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoRemCategory', 'Eliminar categoría de grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLevelsList', 'Mostrar listado de usuariso pro afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoLogout', 'Salir del sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsList', 'Mostrar listado de grupos de usuariso por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesList', 'Listado de afiliados', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersValidationUsernameX', 'Controla la disponibilidad del nombre por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoActivate', 'Activa un usuario inactivo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoAddToGroup', 'Agrega un usuario a un grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLevelsDoDelete', 'Elimina nivel de usuario por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoDelete', 'Elimina usuario por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersWelcome', 'Bienvenida al usuario ingresado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesBranchsDoDelete', 'Elimina sucursal de afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoRemoveFromGroup', 'elimina usuario de un grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoDelete', 'Elimina grupo de usuariso por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLevelsDoEdit', 'Modifica nivel de usuario por afiliado', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoAddUser', 'Agrega usuario por afiliado', 'esp');
