<?php

/**
 * Skeleton subclass for representing a row from the 'orders_stateChanges' table.
 *
 * Cambios de Estado de Pedidos de Productos
 *
 * This class was autogenerated by Propel on:
 *
 * 05/28/07 20:52:58
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class OrderStateChange extends BaseOrderStateChange {

        /*
        * Obtiene el usuario asociado al cambio de estado.
        *
        * @return User/AffiliateUser Usuario asociado
        */
        function getUser() {
                if ($this->getAffiliateId() == "0") {
                        require_once("UserPeer.php");
                        return UserPeer::get($this->getUserId());
                } 
                else
                        return $this->getAffiliateUser();
        }
        
        /*
        * Obtiene el nombre del estado.
        * 
        * @return string Nombre del estado
        */
        function getStateName() {
                require_once("OrderPeer.php");
                return OrderPeer::getStateNameFromNumber($this->getState());
        }        

} // OrderStateChange
