DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Affiliates%' AND `language` = 'eng';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesEdit', 'Edit Affiliates info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLogin', 'Affiliate users login', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersPasswordRecovery', 'Affiliate users password recovery', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesAddAffiliate', 'Add Affiliate', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesBranchsEdit', 'Branch  info edit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoEditUser', 'Save affiliate users info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesViewAffiliate', 'View affiliate info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesDoDelete', 'Delet affiliate', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoAddCategory', 'Add category to affiliate group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoEdit', 'Modify affiliate users groups', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesBranchsList', 'Display Affliates branches list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersList', 'Display Affiliate users list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoRemCategory', 'Delete category from group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLevelsList', 'Display affiliate levels list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoLogout', 'Logout', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsList', 'Display affiliate users groups list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesList', 'Display affiliates list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersValidationUsernameX', 'Check availability of affiliate username', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoActivate', 'Activates an inactive user', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoAddToGroup', 'Add user to affiliate user group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLevelsDoDelete', 'Delete affiliate user level', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoDelete', 'Delete affiliate user ', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersWelcome', 'Welcome to an affiliate user', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesBranchsDoDelete', 'Delete afiliates branch', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoRemoveFromGroup', 'Removes affiliate user from group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersGroupsDoDelete', 'Delete affiliate users group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersLevelsDoEdit', 'Edit affiliate users level', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('AffiliatesUsersDoAddUser', 'Add affliate user ', 'eng');
