DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Catalog%' AND `language` = 'eng';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogAffiliateProductsImport', 'Imports Catalog Affiliate Products ', 'Imports Catalog prices for a specific Affiliate', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogMeasureUnitsEdit', 'CatalogMeasureUnitsEdit', 'CatalogMeasureUnitsEdit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogAffiliateProductCodesEdit', 'CatalogAffiliateProductCodesEdit', 'CatalogAffiliateProductCodesEdit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductCategoriesEdit', 'CatalogProductCategoriesEdit', 'CatalogProductCategoriesEdit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogUnitsEdit', 'CatalogUnitsEdit', 'CatalogUnitsEdit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsEdit', 'CatalogProductsEdit', 'CatalogProductsEdit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogAffiliateProductCodesDoDel', 'CatalogAffiliateProductCodesDoDel', 'CatalogAffiliateProductCodesDoDel', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsDoLoadInCategory', 'CatalogProductsDoLoadInCategory', 'CatalogProductsDoLoadInCategory', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogUnitsDoDelete', 'CatalogUnitsDoDelete', 'CatalogUnitsDoDelete', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsDoDelete', 'CatalogProductsDoDelete', 'CatalogProductsDoDelete', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogPricesAutoUpdate', 'CatalogPricesAutoUpdate', 'CatalogPricesAutoUpdate', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogUnitsList', 'CatalogUnitsList', 'CatalogUnitsList', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogMeasureUnitsList', 'CatalogMeasureUnitsList', 'CatalogMeasureUnitsList', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsDoRemoveCategoriesX', 'CatalogProductsDoRemoveCategoriesX', 'CatalogProductsDoRemoveCategoriesX', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsDoAddCategoriesX', 'CatalogProductsDoAddCategoriesX', 'CatalogProductsDoAddCategoriesX', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogAffiliateProductList', 'CatalogAffiliateProductList', 'CatalogAffiliateProductList', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogMeasureUnitsDoDelete', 'CatalogMeasureUnitsDoDelete', 'CatalogMeasureUnitsDoDelete', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogShow', 'CatalogShow', 'CatalogShow', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsGetImage', 'CatalogProductsGetImage', 'CatalogProductsGetImage', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsDoLoadWithCategory', 'CatalogProductsDoLoadWithCategory', 'CatalogProductsDoLoadWithCategory', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductCategoriesList', 'CatalogProductCategoriesList', 'CatalogProductCategoriesList', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogAffiliateProductCodesList', 'CatalogAffiliateProductCodesList', 'CatalogAffiliateProductCodesList', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductCategoriesGetImage', 'CatalogProductCategoriesGetImage', 'CatalogProductCategoriesGetImage', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductsList', 'CatalogProductsList', 'CatalogProductsList', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('CatalogProductCategoriesDoDelete', 'CatalogProductCategoriesDoDelete', 'CatalogProductCategoriesDoDelete', 'eng');
