DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Orders%' AND `language` = 'eng';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersEdit', 'Edit order', 'Edit order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersImport', 'Import orders', 'Import orders', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersAddItemToCartX', 'Add product to shopping cart', 'Add product to shopping cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersCartDoDelete', 'Empty shopping cart', 'Empty shopping cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersChangeItemCartX', 'Modify item from cart', 'Modify item from cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersConfirm', 'Confirm order', 'Confirm order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoAddToCart', 'Add producto to cart', 'Add producto to cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoDelete', 'Delete order', 'Delete order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoGenerate', 'Generate order', 'Generate order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoSave', 'Save order', 'Save order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersExport', 'Export Orders ', 'Export Orders ', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersExportSaf', 'Export orders to SAF', 'Export orders to SAF', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersItemsDoAddX', 'Delete product from cart', 'Delete product from cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersItemsDoDeleteX', 'Delete item from cart', 'Delete item from cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersItemsDoEditX', 'Edit producto quantity', 'Edit producto quantity', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersList', 'Orders list', 'Orders list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersRemoveItemCartX', 'Remove product from cart', 'Remove product from cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersStateDoChangeX', 'Change order state', 'Change order state', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesDoAddToCart', 'Add order template to shopping cart', 'Add order template to shopping cart', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesDoDelete', 'Delete order template', 'Delete order template', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesList', 'View order templates list', 'View order templates list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesView', 'View orders template', 'View orders template', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersUpdateClients', 'Update client order', 'Update client order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersView', 'View order', 'View order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersViewCart', 'View shopping cart', 'View shopping cart', 'eng');
