DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Orders%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersEdit', 'Modificar orden', 'Modificar orden', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersImport', 'Importar órdenes', 'Importar órdenes', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersAddItemToCartX', 'Agregar producto al carrito de ocmpras', 'Agregar producto al carrito de ocmpras', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersCartDoDelete', 'Vacias carrito de compras', 'Vacias carrito de compras', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersChangeItemCartX', 'Modificar item del carrito', 'Modificar item del carrito', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersConfirm', 'Confirmar pedido', 'Confirmar pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoAddToCart', 'Agregar producto al carrito', 'Agregar producto al carrito', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoDelete', 'Eliminar pedido', 'Eliminar pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoGenerate', 'Generar pedido', 'Generar pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersDoSave', 'Guardar pedido', 'Guardar pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersExport', 'Exportar pedidos', 'Exportar pedidos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersExportSaf', 'Exportar pedidos al SAF', 'Exportar pedidos al SAF', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersItemsDoAddX', 'Agregar producto al carrito', 'Agregar producto al carrito', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersItemsDoDeleteX', 'Eliminar producto dle carrito', 'Eliminar producto dle carrito', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersItemsDoEditX', 'Modificar cantidad en carrito', 'Modificar cantidad en carrito', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersList', 'Ver listado de órdenes', 'Ver listado de órdenes', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersRemoveItemCartX', 'eliminar producto del carrito', 'eliminar producto del carrito', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersStateDoChangeX', 'Cambiar estado de la orden', 'Cambiar estado de la orden', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesDoAddToCart', 'Agregar plantilla al carrito de ocmpras', 'Agregar plantilla al carrito de ocmpras', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesDoDelete', 'Eliminar plantilla de pedido', 'Eliminar plantilla de pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesList', 'Ver lista de plantillas de pedido', 'Ver lista de plantillas de pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersTemplatesView', 'Ver plantilla de pedido', 'Ver plantilla de pedido', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersUpdateClients', 'Actualizar cliente de la orden', 'Actualizar cliente de la orden', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersView', 'Ver orden', 'Ver orden', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('OrdersViewCart', 'Ver carrito de compras', 'Ver carrito de compras', 'esp');
