<?php

  // include base peer class
  require_once 'import/classes/om/BasePurchaseOrderPeer.php';

  // include object class
  include_once 'import/classes/PurchaseOrder.php';


/**
 * Skeleton subclass for performing query and update operations on the 'import_purchaseOrder' table.
 *
 * Orden de Pedido a Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class PurchaseOrderPeer extends BasePurchaseOrderPeer {

} // PurchaseOrderPeer
