<?php

  // include base peer class
  require_once 'import/classes/om/BasePurchaseOrderItemPeer.php';

  // include object class
  include_once 'import/classes/PurchaseOrderItem.php';


/**
 * Skeleton subclass for performing query and update operations on the 'import_purchaseOrderItem' table.
 *
 * Elemento de Orden de Pedido a Cliente
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class PurchaseOrderItemPeer extends BasePurchaseOrderItemPeer {

} // PurchaseOrderItemPeer
