DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Modules%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEdit', 'Editar información del módulo', 'Edita información del módulo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesEdit', 'Editar información de entidades', 'Edita información de entidades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesFieldsEdit', 'Editar campos de entidades', 'Edita campos de entidades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallFileCheck', 'Verificación de existencia de archivos para instalación', 'Verifica existencia de archivos para instalación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallSetupActionsLabel', 'Administrar etiquetas de acciones', 'Administra etiquetas de acciones durante instalación del módulo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallSetupMessages', 'Administrar mensajes del sistema', 'Administra mensajes del sistema durante instalación del módulo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallSetupModuleInformation', 'Administrar información del módulo', 'Administra información del módulo durante su instalación ', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallSetupPermissions', 'Administrar permisos de acciones', 'Administra permisos de acciones durante instalación del módulo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesDoActivateX', 'Activar módulo', 'Activa módulo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesAutocompleteListX', 'Atucompletar entidades de módulos', 'Muestra lista entidades de módulos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesCreate', 'Crear entidades', 'Crea entidades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesFieldsList', 'Ver los campos de entidades disponibles', 'Muestra los campos de entidades disponibles', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesFieldsListX', 'Obtener las entidades disponibles en el sistema via Ajax', 'Obtiene las entidades disponibles en el sistema via Ajax', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesImportSchemas', 'Importar esquemas de xml', 'Importa esquemas de xml', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesList', 'Ver las entidades disponibles', 'Muestra las entidades disponibles', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesSchemaExport', 'Exportar esquema de la base de datos', 'Exporta esquema en formato xml de la base de datos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesSchemaGet', 'Otener xml de entidades', 'Obtiene el esquema de entidades en formato xml', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesEntitiesSqlGet', 'Obtener información sql de entidades', 'Obtiene la información sql de entidades', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesExtra', 'Mostrar información adicional', 'Muestra información adicional', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallList', 'Listar modulos para instalación', 'Listdo de modulos para instalación/reinstalación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallModuleInformationSetup', 'Administrar información del módulo', 'Administra información del módulo para instalación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallSetupSelectLanguages', 'Administrar idiomas de instalación', 'Permite la selección de idiomas para instalación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesInstallUnchecked', 'Instalar múltiples módulos', 'Instala múltiples módulos simultáneamente', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesList', 'Listar módulos del sistema', 'Listado de módulos del sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('ModulesRemoveActionX', 'Eliminar acciones del sistema', 'Elimina físicamente la acción (script) del servidor', 'esp');
