DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Documents%' AND `language` = 'esp';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsEdit', 'Alta/Modificación de documentos', 'Permite dar de alta o editar documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsCategoriesList', 'Listar documentos por categoría', 'Lista documentos por categoría', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsDoDelete', 'Eliminar documentos', 'Elimina documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsDoDeleteX', 'Eliminar documento por ajax', 'Elimina documentos por ajax', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsDoDownload', 'Descargar de documentos', 'Permite la descarga de documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsList', 'Listar documentos disponibles', 'Muestra el listado de documentos disponibles', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsShow', 'Listado público de documentos', 'Listado público de documentos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `description` ,`language` ) VALUES ('DocumentsUpload', 'Agregar documento al servidor', 'Agrega el archivo electrónico al servidor', 'esp');
