DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Users%' AND `language` = 'eng';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLogin', 'Users login', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordRecovery', 'Password Recovery', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersEdit', 'User edit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordChange', 'Password modification', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoLinkToSupplier', 'User link to supplier', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersEditInfo', 'Edit User Info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoDeleteFromGroupX', 'Remove user from group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoEditInfoX', 'Edit user info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLoginMaintenance', 'Users login under maintenance', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLevelsDoDelete', 'Delete user level', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoAddCategoryToGroup', 'Add category to group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoLogout', 'User logout', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLevelsDoEdit', 'Edit user level', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoAddToGroupX', 'Add user to group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoEdit', 'Group edit', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordRecoverySendConfirmationRequest', 'Request Password recovery confirmation', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLevelsList', 'Users level list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersList', 'Users list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoDelete', 'Group deletion', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoDelete', 'Delete user', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoActivateX', 'Activate user', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersValidationPasswordX', 'Verify current passwort in order to change it', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersValidationUsernameX', 'Verify availability/validation of username', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordDoChangeForRecovery', 'Change password from recovery', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordResetX', 'Reset password', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsList', 'Groups list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoActivate', 'User activation', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersAutocompleteListX', 'Autocomplete users list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersWelcome', 'User welcome', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoRemoveCatFromGroup', 'Remove a category from group', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersCaptchaGeneration', 'Creates captcha', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordRecoveryConfirmation', 'Confirm password recovery', 'eng');
