DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Users%' AND `language` = 'esp';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLogin', 'Ingreso al sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordRecovery', 'Recuperar contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersEdit', 'Modificar Información del Usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordChange', 'Modificación de contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoLinkToSupplier', 'Enlazar usuario a proveedor', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersEditInfo', 'Modificar Información del Usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoDeleteFromGroupX', 'Eliminar usuario de grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoEditInfoX', 'Editar información de Usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLoginMaintenance', 'Ingreso al sistema en mantenimiento', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLevelsDoDelete', 'Eliminar nivel de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoAddCategoryToGroup', 'Agregar categoría a grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoLogout', 'Salir del sistema', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLevelsDoEdit', 'Editar nivel de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoAddToGroupX', 'Agregar usuario a grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoEdit', 'Editar grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordRecoverySendConfirmationRequest', 'Enviar confirmación de nueva contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersLevelsList', 'Lista de niveles de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersList', 'Lista de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoDelete', 'Eliminar grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoDelete', 'Eliminar usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoActivateX', 'Activar usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersValidationPasswordX', 'Verifica contraseña actual para su modificación', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersValidationUsernameX', 'Verifica validez/disponibilidad de nombre de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordDoChangeForRecovery', 'Cambiar contraseña recuperada', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordResetX', 'Resetear contraseña', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsList', 'Lista de grupos', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersDoActivate', 'Activación de usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersAutocompleteListX', 'Autocompletar usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersWelcome', 'Página de bienvenida al usuario', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersGroupsDoRemoveCatFromGroup', 'Eliminar categoría de un grupo', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersCaptchaGeneration', 'Generar imagen de seguridad', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('UsersPasswordRecoveryConfirmation', 'Confirmar recupero de contraseña', 'esp');
