<?php

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [10/23/06 13:29:49]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package infocivica 
 */
class Document {

	var $id;
	var $realFilename;
	var $date;
	var $categoryId;
	var $description;
	var $documentDate;
	var $password;
	var $title;

	function setId($id) {
		$this->id = $id;
	}
	
	function setRealFilename($realFilename) {
		$this->realFilename = $realFilename ;		
	}
	
	function setDate($date) {
		$this->date = $date;		
	}
	
	function setCategoryId($categoryId) {
		$this->categoryId = $categoryId;		
	}
	
	function setDescription($description) {
		$this->description = $description;		
	}
	
	function setDocumentDate($documentDate) {
		$this->documentDate = $documentDate;		
	}
	
	function setPassword($password) {
		$this->password = $password;		
	}
	
	function setTitle($title) {
		$this->title = $title;		
	}
	
	function getId() {
		return $this->id;
	}

	function getRealFilename() {
		return $this->realFilename;
	}

	function getDate() {
		return $this->date;
	}

	function getCategoryId() {
		return $this->categoryId;
	}

	function getDescription() {
		return $this->description;
	}

	function getDocumentDate() {
		return $this->documentDate;
	}

	function getPassword() {
		return $this->password;
	}

	function getTitle() {
		return $this->title;
	}

	/**
	 * Indica si un documento esta protegido por password
	 * @return boolean
	 */
	 function isPasswordProtected() {
		if ($this->getPassword() == '')
			return false;
		
		return true;
	}

	/**
	 * Realiza la verificacion de password
	 * @param string password
	 * @return boolean
	 */
	 function checkPassword($password) {
		if ($this->getPassword() == md5($password."ASD") ) {
			return true;
		}
		return false;
	}
	
	/**
	 * Obtencion de contenidos y los escribi en la salida estandart
	 *
	 *
	 */
	 function getContents() {

		global $system;
		$documentsPath = $system['config']['documents']['documentsPath'];
		readfile($documentsPath . '/' . $this->getId());
		
	}
	
	function save() {
		
		global $tablePrefix;
		$prefix = $tablePrefix . 'documents_';
		$db = new DBConnection();
		
		if ($this->getId() == '') 
			$query = "INSERT INTO ". $prefix . "document(realFilename,date,categoryId,description,document_date,password,title) VALUES('" . $this->getRealFilename() . "','" . $this->getDate() . "','" . $this->getCategoryId() . "','" . $this->getDescription() . "','" . $this->getDocumentDate() . "','" . $this->getPassword() . "','" . $this->getTitle() . "')";
		else
			$query = "UPDATE ". $prefix . "document SET realFilename = '" . $this->getRealFilename() . "' ,date = '" . $this->getDate() . "', categoryId = '" . $this->getCategoryId() . "', description = '" . $this->getDescription() . "', document_date = '" . $this->getDocumentDate() . "',password = '" . $this->getPassword() . "',title = '" . $this->getTitle() . "' WHERE id = " . $this->getId();
		
		$db->query($query);
		
		if($db->affected_rows()>0) {
			
			$this->setId($db->getId());
			
			return $this;
		}
		else return false;
		
		
	}
	
	function delete() {

		global $tablePrefix;
		$prefix = $tablePrefix . 'documents_';		
		$db = new DBConnection();
				
		$query = "DELETE FROM ". $prefix . "document WHERE id = " . $this->getId();
		$db->query($query);
		if($db->affected_rows()>0)
			return true;
		else 
			return false;
		
	}
}
