<?php
    $msg['t01'] = 'Name:';
	$msg['t02'] = 'Name2:';
	$msg['t03'] = 'City:';
	$msg['t04'] = 'Alter:';
	$msg['t05'] = 'E-mail:';
	$msg['t06'] = 'MSN Messenger:';
	$msg['t07'] = 'Homepage/Website:';
	$msg['t08'] = 'Link:';
	$msg['t09'] = 'Link2 :';
	$msg['t10'] = 'ICQ:';
	$msg['t11'] = 'Andere:';
	$msg['t12'] = 'Foto Link:';
	$msg['t13'] = 'Kommentare:';
	$msg['t14'] = 'Speichern';
	$msg['t15'] = 'Zeige mein Flash-Chat Profil';
	$msg['t16'] = ' (Klick erst "Speichern" wenn du jedes Feld ge&#228;ndert hast!)';
	$msg['t17'] = 'Es besteht kein Profil zu dieser Userid ';
	$msg['t18'] = 'Flash-Chat Profil f&#252;r ';
	$msg['t19'] = ' Flash-Chat Profil';
	$msg['t20'] = 'Lade Foto';
	$msg['t21'] = ' Lade ein Foto (wenn du willst) zu dem Flash-Chat Server';
	$msg['t22'] = 'Andere Flash-Chat Profile';
	$msg['t23'] = 'Kann dieses Dateiformat nicht hochladen.<br>Schlie&#223;e dieses Fenster und versuche es nocheinmal.<br>Es werden folgende Dateiformate unterst&#252;tzt: ';
	$msg['t24'] = 'Dateigr&#246;&#223;e ';
	$msg['t25'] = ' KByte. Zu gro&#223;e Datei.<br>Schlie&#223;e dieses Fenster und versuche es nocheinmal.<br>Maximal Dateigr&#246;&#223;e ist: ';
	$msg['t26'] = 'Kann dieses Bild nicht kopieren !<br>Schlie&#223;e dieses Fenster und versuche es nocheinmal.';
	$msg['t27'] = 'Keine Datei zum hochladen.<br>Schlie&#223;e dieses Fenster und versuche es nocheinmal.';
	$msg['t28'] = '<b>Suche (Browse)</b> nach Deinem Foto auf Deinem PC - Dann klick <b>Lade Foto</b>';
	$msg['t29'] = 'Dateiformate, die hochgeladen werden k&ouml;nnen: ';
	$msg['t30'] = 'Die Maximal Dateigr&ouml;&szlig;e die hochgeladen werden kann betr&#228;gt ';
	$msg['t31'] = 'Lade Foto';
	$msg['t32'] = 'Flash-Chat - Upload eines Fotos f&#252;r Dein Profil';
	$msg['t33'] = 'Es gibt keine Flash-Chat Profile';
	$msg['t34'] = 'Klick auf das Foto um das Original Foto zu sehen. Aktuell ist die Fotogr&#246&szlig;e beschr&#228;nkt auf ' . $pictureWidth . ' Pixel Breite';
	$msg['t35'] = 'Aktuelles Passwort';
	$msg['t36'] = 'Neues Passwort';
	$msg['t37'] = 'Benutze nur diese drei Felder um Dein Passwort zu &#228;ndern';
	$msg['t38'] = 'Dein Passwort wurde erfolgreich aktualisiert';
	$msg['t39'] = 'Dein Passwort wurde nicht aktualisiert';
	$msg['t40'] = 'Gebe das Alte/Neue Passwort ein';
	$msg['t41'] = 'AIM:';
	$msg['t42'] = 'YIM:';
	$msg['t43'] = 'Geschlecht:';
	$msg['t44'] = 'Location:';
	$msg['t45'] = 'Zeige dieses Foto';
	$msg['t46'] = 'Zeige dieses Profil';
	$msg['t47'] = 'Neues Flash-Chat Passwort';
	$msg['t48'] = 'Dein  registrierter Nickname:';
	$msg['t49'] = 'Deine registrierte Email-Addresse:';
	$msg['t50'] = 'Passwort senden';
	$msg['t51'] = 'Neues Flash-Chat Passwort f&#252;r';  			// mail subject
	$msg['t52'] = 'Dein neues Flash-Chat Passwort ist:';		// mail body text
	$msg['t53'] = 'Mit freundlichen Gr&#252;&#223;en das Flash-Chat Team.';		// any terminating mail body text
	$msg['t54'] = 'Dein neues Flash-Chat Passwort wurde an Deine E-Mail-Adresse gesandt';
	$msg['t55'] = 'Error: Kann Deinen Nickname oder Deine Email-Addresse nicht finden.';
	$msg['t56'] = 'Passwort Seite';
	$msg['t57'] = 'Passwort Ausschu&#223; - Seite';
	$msg['t58'] = 'Flash-Chat Startseite';
	$msg['t59'] = 'Error: Konnte die Mail nicht an Deine Email-Addresse senden. Passwort wurde nicht ge&#228;ndert.';
	$msg['t60'] = 'Error: Deine E-Mail-Adresse ist nicht g&#252;ltig.<br>Bitte kontaktier den Flash-Chat Administrator.<br>';
	$msg['t61'] = 'Aktuelles Flash-Chat Passwort';
	$msg['t62'] = 'Sende aktuelles Passwort';
	$msg['t63'] = 'Aktuelles Flash-Chat Passwort f&#252;r';  			// mail subject
	$msg['t64'] = 'Dein aktuelles Flash-Chat Passwort ist:';			// mail body text
	$msg['t65'] = 'Dein aktuelles Flash-Chat Passwort wurde an Deine Email-Addresse gesendet';
	$msg['t66'] = 'Best&#228;tige neues Passwort';
	$msg['t67'] = 'Das Passwort was du eingegeben hast stimmt nicht &#252;berein';
	$msg['t68'] = 'Keine Fotos f&#252;r:';
	$msg['t69'] = 'Editieren';

	$msg['t100'] = 'Benutzername [user_name] ist bereits vergeben. Bitte w&#228;hle einen anderen Benutzername.';
	$msg['t101'] = 'Neue Flash-Chat Benutzerregistrierung';
	$msg['t102'] = 'M&#228;nnlich';
	$msg['t103'] = 'Weiblich';
	$msg['t104'] = 'Andere';
	$msg['t105'] = 'Danke !';
	$msg['t106'] = 'Benutzer <b>[user_name]</b> wurde erfolgreich registriert.<br>Du kannst Dich nun mit Deinem Flash-Chat Benutzername und Passwort in den Chat einloggen.';
	$msg['t107'] = '';
	$msg['t108'] = 'Starte Flash-Chat';
	$msg['t109'] = 'Bitte fuelle das Benutzernamefeld aus';
	$msg['t110'] = 'Bitte spezifiziere Dein Passwort ';
	$msg['t111'] = 'Die von Dir eingegebenen Passwoerter stimmen nicht ueberein .';
	$msg['t112'] = 'Benutzername:';
	$msg['t113'] = 'Passwort:';
	$msg['t114'] = 'Bestaetige das Passwort:';
	$msg['t115'] = 'Benutzerrechte:';
	$msg['t116'] = 'normaler User';
	$msg['t117'] = 'Administrator';
	$msg['t118'] = 'Spy';
	$msg['t119'] = 'Du kannst sp&#228;ter Dein Profil nochmals bearbeiten,<br>wenn Du im Flash-Chat bist, klicke einfach auf Deinen Benutzernamen mit der linken Maustaste und anschlie&szlig;end auf Profil'; 
	$msg['t120'] = 'Du musst Deinen registrierten Name<br>und Deine registrierte E-Mail-Adresse in Deiner Profilseite eingeben'; 
	$msg['t121'] = ''; 
	$msg['t122'] = ''; 
	
	$msg['t123'] = 'Customer';
	$msg['t124'] = 'The file that you uploaded may contain scripting elements, which could pose a security risk. Please try another file.';	
?>