<?php
    $msg['t01'] = 'Nome:';
	$msg['t02'] = 'Altri Nomi:';
	$msg['t03'] = 'Luogo:';
	$msg['t04'] = 'Anni:';
	$msg['t05'] = 'E-mail:';
	$msg['t06'] = 'MSN Messenger:';
	$msg['t07'] = 'Sito Internet:';
	$msg['t08'] = 'Altro link:';
	$msg['t09'] = 'Altro link testuale:';
	$msg['t10'] = 'ICQ:';
	$msg['t11'] = 'Altro:';
	$msg['t12'] = 'Foto personale:';
	$msg['t13'] = 'Interessi:';
	$msg['t14'] = 'Salva';
	$msg['t15'] = 'Mostra il profilo di questo utente';
	$msg['t16'] = ' (clicca "Salva" se hai cambiato qualche informazione!)';
	$msg['t17'] = 'Nessun profilo inerente a questo utente';
	$msg['t18'] = 'Profilo di ';
	$msg['t19'] = ' Profilo';
	$msg['t20'] = 'Carica la Foto';
	$msg['t21'] = '';// Carica una foto, se preferisci, sul nostro server
	$msg['t22'] = 'Altri profili di utenti';
	$msg['t23'] = 'Errore<br><br>Non puoi inserire questo tipo di file.<br>Prova di nuovo.<br>Sono ammessi solo questi tipi di files: ';
	$msg['t24'] = 'Errore<br><br>Grandezza del file';
	$msg['t25'] = ' KB. File troppo grande.<br>Prova di nuovo.<br>Grandezza massima del file ';
	$msg['t26'] = 'Errore<br><br>Non puoi copiare la foto!<br>Chiudi questa finestra e prova di nuovo.';
	$msg['t27'] = 'Errore<br><br>Nessun file da caricare.<br>Chiudi questa finestra e prova di nuovo.';
	$msg['t28'] = 'Cerca la foto nel tuo computer, poi clicca su "Carica Immagine"';
	$msg['t29'] = 'I tipi di file permessi sono ';
	$msg['t30'] = 'Grandezza massima dei files da caricare ';
	$msg['t31'] = 'Carica la foto';
	$msg['t32'] = 'Carica la tua foto personale';
	$msg['t33'] = 'Non ci sono profili presenti in chat';
	$msg['t34'] = 'Clicca sulla foto per vedere la versione originale. Dimensione della foto limitata a ' . $pictureWidth . ' pixels width';
	$msg['t35'] = 'Vecchia Password';
	$msg['t36'] = 'Nuova Password';
	$msg['t37'] = 'Usa questi tre campi<br>solo se vuoi cambiare la password';
	$msg['t38'] = 'Password cambiata con successo';
	$msg['t39'] = 'Errore: password non aggiornata';
	$msg['t40'] = 'Errore: Scrivi sia la vecchia che la nuova password';
	$msg['t41'] = 'AIM:';
	$msg['t42'] = 'YIM:';
	$msg['t43'] = 'Genere:';
	$msg['t44'] = 'Luogo:';
	$msg['t45'] = 'Mostra questa foto';
	$msg['t46'] = 'Mostra questo profilo';
	$msg['t47'] = 'Nuova Password';
	$msg['t48'] = 'Il tuo nickname:';
	$msg['t49'] = 'La tua <NOBR>e-mail</NOBR>:';
	$msg['t50'] = 'Salva la nuova password';
	$msg['t51'] = 'La nuova password di';  			// mail subject
	$msg['t52'] = 'Nuova password:';		// mail body text
	$msg['t53'] = 'Lo staff ti ringrazia.';		// any terminating mail body text
	$msg['t54'] = 'Nuova password spedita alla e-mail che hai indicato';
	$msg['t55'] = 'Errore:<br>Nickname ed e-mail non trovati.';
	$msg['t56'] = 'Pagina registrazione password';
	$msg['t57'] = 'Pagina di rifiuto password';
	$msg['t58'] = 'Pagina iniziale della Chat';
	$msg['t59'] = 'Errore:<br>E-mail non inviata a causa della Password non cambiata.';
	$msg['t60'] = 'Errore:<br>Il tuo indirizzo e-email presenta degli errori.<br>Per informazioni contatta il proprietario del sito.<br>';
	$msg['t61'] = 'Ricorda la tua Password';
	$msg['t62'] = 'Scrivi la tua password';
	$msg['t63'] = 'Password attuale della Chat';  			// mail subject
	$msg['t64'] = 'La tua attuale Password:';			// mail body text
	$msg['t65'] = 'Attuale Password spedita al tuo indirizzo e-mail';
	$msg['t66'] = 'Conferma la nuova password';
	$msg['t67'] = 'Le password che hai scritto non combaciano';
	$msg['t68'] = 'Nessuna foto presente';
	$msg['t69'] = 'Modifica';

	$msg['t100'] = 'Utente [user_name] esistente nei nostri archivi. Scegli un altro username.';
	$msg['t101'] = 'Registrazione nuovo utente';
	$msg['t102'] = 'Maschio';
	$msg['t103'] = 'Femmina';
	$msg['t104'] = 'Non specificare';
	$msg['t105'] = 'Grazie!';
	$msg['t106'] = 'Utente <b>[user_name]</b> registrato con successo.<br>Ora puoi connetterti alla Chat con il tuo username e password.';
	$msg['t107'] = '';
	$msg['t108'] = 'Apri la Chat';
	$msg['t109'] = 'Inserisci il tuo username nel campo corretto';
	$msg['t110'] = 'Specifica la tua password';
	$msg['t111'] = 'Le password che hai inserito non combaciano.';
	$msg['t112'] = 'User name:';
	$msg['t113'] = 'Password:';
	$msg['t114'] = 'Conferma Password:';
	$msg['t115'] = 'Ruolo Utente:';
	$msg['t116'] = 'Utente Standard';
	$msg['t117'] = 'Moderatore';
	$msg['t118'] = 'Spia';
	$msg['t119'] = 'Puoi modificare il tuo profilo anche in un secondo momento,<br>quando entri in Chat, clicca sul tuo nome nella lista utenti'; 
	$msg['t120'] = 'Devi fornire il tuo nickname ed indirizzo <NOBR>e-mail</NOBR>.'; 
	$msg['t121'] = ''; 
	$msg['t122'] = ''; 
	
	$msg['t123'] = 'Cliente';
	$msg['t124'] = 'The file that you uploaded may contain scripting elements, which could pose a security risk. Please try another file.';		
?>