<?php
    $msg['t01'] = 'Full Name:';
	$msg['t02'] = 'Name2:';
	$msg['t03'] = 'City:';
	$msg['t04'] = 'Age:';
	$msg['t05'] = 'E-mail:';
	$msg['t06'] = 'MSN Messenger:';
	$msg['t07'] = 'Website:';
	$msg['t08'] = 'Other link:';
	$msg['t09'] = 'Other link text:';
	$msg['t10'] = 'ICQ:';
	$msg['t11'] = 'Other:';
	$msg['t12'] = 'Picture link:';
	$msg['t13'] = 'Interests:';
	$msg['t14'] = 'Save';
	$msg['t15'] = 'Show this FlashChat Profile';
	$msg['t16'] = ' (click "Save" first if you have changed any field!)';
	$msg['t17'] = 'No profile exist for this userid ';
	$msg['t18'] = 'FlashChat Profile for ';
	$msg['t19'] = ' FlashChat Profile';
	$msg['t20'] = 'Load Portaint';
	$msg['t21'] = ' Load a picture (if you want) to the FlashChat server';
	$msg['t22'] = 'Other FlashChat Profiles';
	$msg['t23'] = 'Error<br><br>Can not upload this file type.<br>Please try again.<br>Only these filetypes are allowed: ';
	$msg['t24'] = 'Error<br><br>File size ';
	$msg['t25'] = ' KB. The file is too big.<br>Please try again.<br>Max file size is ';
	$msg['t26'] = 'Error<br><br>Can not copy the picture !<br>Close this window and try again.';
	$msg['t27'] = 'Error<br><br>No file to upload.<br>Close this window and try again.';
	$msg['t28'] = 'Browse for the image on your computer, then click "Load Portaint"';
	$msg['t29'] = 'Allowed file types are ';
	$msg['t30'] = 'Maximum file size for upload is ';
	$msg['t31'] = 'Load picture';
	$msg['t32'] = 'Upload your Profile Portaint';
	$msg['t33'] = 'There are no FlashChat profiles';
	$msg['t34'] = 'Click on the picture to see original picture. Current picture size is limited to ' . $pictureWidth . ' pixels width';
	$msg['t35'] = 'Current password';
	$msg['t36'] = 'New password';
	$msg['t37'] = 'Use these three fields<br>only if you want to change the password';
	$msg['t38'] = 'The password was updated successfully';
	$msg['t39'] = 'Error: The password was not updated';
	$msg['t40'] = 'Error: Enter both old/new password';
	$msg['t41'] = 'AIM:';
	$msg['t42'] = 'YIM:';
	$msg['t43'] = 'Gender:';
	$msg['t44'] = 'Location:';
	$msg['t45'] = 'Show this Picture';
	$msg['t46'] = 'Show this Profile';
	$msg['t47'] = 'New Password';
	$msg['t48'] = 'Your registered nickname:';
	$msg['t49'] = 'Your registered e-mail address:';
	$msg['t50'] = 'Send new password';
	$msg['t51'] = 'New FlashChat password for';  			// mail subject
	$msg['t52'] = 'Your new FlashChat password is:';		// mail body text
	$msg['t53'] = 'Thanks from the FlashChat team.';		// any terminating mail body text
	$msg['t54'] = 'Your new FlashChat password has been sent to your email address';
	$msg['t55'] = 'Error:<br>Could not find either your Nick name or your email address.';
	$msg['t56'] = 'Password page';
	$msg['t57'] = 'Password reject page';
	$msg['t58'] = 'FlashChat start page';
	$msg['t59'] = 'Error:<br>Could not send mail to your email address. Password not changed.';
	$msg['t60'] = 'Error:<br>Your email address field does not pass our validation rules.<br>Please contact FlashChat administrator.<br>';
	$msg['t61'] = 'Password Reminder';
	$msg['t62'] = 'Send current password';
	$msg['t63'] = 'Current FlashChat password for';  			// mail subject
	$msg['t64'] = 'Your current FlashChat password is:';			// mail body text
	$msg['t65'] = 'Your current FlashChat password has been sent to your email address';
	$msg['t66'] = 'Confirm new password';
	$msg['t67'] = 'The passwords you entered do not match';
	$msg['t68'] = 'No picture to show';
	$msg['t69'] = 'Edit';

	$msg['t100'] = 'User [user_name] already existing or invalid. Please choose another username.';
	$msg['t101'] = 'New User Registration';
	$msg['t102'] = 'Male';
	$msg['t103'] = 'Female';
	$msg['t104'] = 'Other';
	$msg['t105'] = 'Thank You !';
	$msg['t106'] = 'User <b>[user_name]</b> has been successfully registered.<br>You may now login to FlashChat with your username and password.';
	$msg['t107'] = '';
	$msg['t108'] = 'Start FlashChat';
	$msg['t109'] = 'Please fill in username field';
	$msg['t110'] = 'Please specify password';
	$msg['t111'] = 'The passwords you entered do not match.';
	$msg['t112'] = 'User name:';
	$msg['t113'] = 'Password:';
	$msg['t114'] = 'Confirm Password:';
	$msg['t115'] = 'User Role:';
	$msg['t116'] = 'Regular User';
	$msg['t117'] = 'Administrator';
	$msg['t118'] = 'Spy';
	$msg['t119'] = 'You can later modify your profile,<br>when in FlashChat, by clicking your name in the room list'; 
	$msg['t120'] = 'You must provide your profile nickname and e-mail address.'; 
	$msg['t121'] = ''; 
	$msg['t122'] = '';
	
	$msg['t123'] = 'Customer';
	$msg['t124'] = 'The file that you uploaded may contain scripting elements, which could pose a security risk. Please try another file.';	 
?>