<?php

/** 
 * The skeleton for this class was autogenerated by Propel  on:
 *
 * [04/09/07 18:45:45]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package anmaga 
 */
class ProductCategory extends BaseProductCategory {

}
